services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  db-migrate:
    image: migrate/migrate
    command: -path=/migrations -database postgres://postgres:postgres@postgres-db:5432/task?sslmode=disable up
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres-db:
        condition: service_healthy

  task-app:
    build: .
    ports:
      - "44044:44044"
    environment:
      - CONFIG_PATH=/app/config/local.yaml
    depends_on:
      db-migrate:
        condition: service_completed_successfully
volumes:
  pgdata:
