services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db-migrate:
    image: migrate/migrate
    command: -path=/migrations -database postgres://postgres:postgres@postgres-db:5432/task?sslmode=disable up
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres-db

  task-app:
    build: .
    ports:
      - "44044:44044"
    environment:
      - CONFIG_PATH=/app/config/local.yaml
    depends_on:
      - db-migrate
volumes:
  pgdata:
